version: '3'

tasks:
  watch:
    desc: Run all checks whenever a change occurs.
    cmds:
      - clear
      - task: lint
      - task: build-all
    sources:
      - "flake.nix"
      - "src/**/*.nix"
    watch: true
    interval: 1s

  # Build and change to the current configuration.
  # This task uses the systems current username and hostname to determine if it is a
  # home manager or nixos.
  switch:
    desc: Rebuild and switch your configurations.
    vars:
      HOST:
        sh: hostname
      USER:
        sh: whoami
    cmds:
      - task: switch-{{.USER}}-{{.HOST}}

  # Hidden tasks to dispatch the specific user system combo to switch-hm or switch-nixos.
  switch-kevinfrench-MSS01-T4: {cmds: [task: switch-hm]}
  switch-kdfrench-hagrid: {cmds: [task: switch-nixos]}
  switch-kdfrench-hedwig: {cmds: [task: switch-nixos]}

  # Build and change the home manager configuration.
  switch-hm:
    vars:
      # It only makes sense to run this command for the current running system so
      # the vars get the current system information.
      HOST:
        sh: hostname
      USER:
        sh: whoami
    cmds:
      - home-manager switch --flake .#{{.USER}}@{{.HOST}}

  # Build and change the nixos configuration.
  switch-nixos:
    cmds:
      - sudo nixos-rebuild switch

  # Build but don't change your configuration.
  # This task uses the systems current username and hostname to determine if it is a
  # home manager or nixos.
  build:
    desc: Build the your host configuration but don't activate or add to boot.
    vars:
      HOST:
        sh: hostname
      USER:
        sh: whoami
    cmds:
      - task: build-{{.USER}}-{{.HOST}}

  # Hidden tasks to dispatch the specific user system combo to build-hm or build-nixos.
  build-kevinfrench-MSS01-T4: {cmds: [{task: build-hm, vars: {HOST: MSS01-T4, USER: kevinfrench}}]}
  build-kdfrench-hagrid: {cmds: [{task: build-nixos, vars: {HOST: hagrid}}]}
  build-kdfrench-hedwig: {cmds: [{task: build-nixos, vars: {HOST: hedwig}}]}

  # Build for every system user combo.
  build-all:
    desc: Build all configurations.
    cmds:
      - task: build-kevinfrench-MSS01-T4
      - task: build-kdfrench-hagrid
      - task: build-kdfrench-hedwig

  # Builds a nixos configuration.
  # var HOST - required, the host to build.
  build-nixos:
    cmds:
      # Using nix build instead of nixos-rebuild command enables us to build in ci and on
      # non-nixos systems.
      - nix build .#nixosConfigurations.{{.HOST}}.config.system.build.toplevel

  # Builds a hm configuration.
  # var HOST - required, the host to build.
  # var USER - required, the user to build.
  build-hm:
    cmds:
      - home-manager build --flake .#{{.USER}}@{{.HOST}}

  update:
    desc: Updates all flake inputs.
    cmds:
      - nix flake update

  garbage-collect:
    desc: Removes unused nix/store paths.
    cmds:
      - nix-collect-garbage

  list-generations:
    desc: List nix-os generations.
    cmds:
      - sudo nix-env --list-generations --profile /nix/var/nix/profiles/system

  delete-generations-older-than-*:
    desc: Delete nix-os generations older than argument.
    vars:
      BEFORE: "{{index .MATCH 0}}"
    cmds:
      - sudo nix-env --delete-generations --profile /nix/var/nix/profiles/system {{.BEFORE}}

  make-boot-space:
    desc: Removes old generations garbage collects and switches to clear out boot.
    cmds:
      - task: delete-generations-older-than-30d
      - task: garbage-collect
      - task: switch

  format:
    desc: Format all nix files.
    cmds:
      - for: sources
        cmd: nixfmt {{ .ITEM }}
    sources:
      - "flake.nix"
      - "src/**/*.nix"

  lint:
    desc: Check if all files meet standards.
    cmds:
      - task: nixfmt-check
      - task: static-analysis
    sources:
      - "flake.nix"
      - "src/**/*.nix"

  nixfmt-check:
    desc: Check if all files are formatted correctly.
    cmds:
      - for: sources
        cmd: nixfmt -c {{ .ITEM }}
    sources:
      - "flake.nix"
      - "src/**/*.nix"

  static-analysis:
    desc: Check if all files meet statix analysis.
    cmds:
      - for: sources
        cmd: statix check {{ .ITEM }}
    sources:
      - "flake.nix"
      - "src/**/*.nix"

  dev-zshell:
    desc: Drop into a zsh with all dev dependencies.
    cmds:
      - devbox run zsh
    interactive: true
