version: '3'

tasks:
  watch:
    desc: Run all checks whenever a change occurs.
    cmds:
      - clear
      - task: lint
    sources:
      - ./**/*.nix
      - exclude: ./.devbox/**/*.nix
    watch: true
    interval: 1s

  switch:
    desc: Rebuild and switch nixos configurations.
    cmds:
      - sudo nixos-rebuild switch

  update:
    desc: Updates all flake inputs.
    cmds:
      - nix flake update

  garbage-collect:
    desc: Removes unused nix/store paths.
    cmds:
      - nix-collect-garbage

  format:
    desc: Format all nix files.
    cmds:
      - for: sources
        cmd: nixfmt {{ .ITEM }}
    sources:
      - ./**/*.nix
      - exclude: ./.devbox/**/*.nix

  lint:
    desc: Check if all files meet standards.
    cmds:
      - task: nixfmt-check
      - task: static-analysis
    sources:
      - ./**/*.nix
      - exclude: ./.devbox/**/*.nix

  nixfmt-check:
    desc: Check if all files are formatted correctly.
    cmds:
      - for: sources
        cmd: nixfmt -c {{ .ITEM }}
    sources:
      - ./**/*.nix
      - exclude: ./.devbox/**/*.nix

  static-analysis:
    desc: Check if all files meet statix analysis.
    cmds:
      - for: sources
        cmd: statix check {{ .ITEM }}
    sources:
      - ./**/*.nix
      - exclude: ./.devbox/**/*.nix

  dev-zshell:
    desc: Drop into a zsh with all dev dependencies.
    cmds:
      - devbox run zsh
    interactive: true
