name: ci
on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: lint
        run: devbox run -- task lint

      - name: build-all
        run: devbox run -- task build-all
